export type PromptTopic={id:string;label:string;short:string;description:string};
export const promptTopics:PromptTopic[]=[
{id:'swap',label:'Swap',short:'Build a premium Solana token swap interface.',description:'Token swap flows, liquidity details, fee panels, routing, and mobile-friendly execution layouts.'},
{id:'meme-token-ui',label:'Meme Token UI',short:'Create a viral Solana meme token landing and dashboard.',description:'Hero sections, tokenomics cards, charts, community modules, and onboarding flows for meme launches.'},
{id:'launchpad',label:'Launchpad',short:'Generate a Solana launchpad product surface.',description:'Raise progress, whitelist states, allocation tables, countdowns, and campaign admin tooling.'},
{id:'protocol-dashboard',label:'Protocol Dashboard',short:'Build a protocol command center with metrics and operations.',description:'Treasury, TVL, governance metrics, validator snapshots, and team-only admin controls.'},
{id:'wallet-ux',label:'Wallet UX',short:'Design wallet onboarding, balances, and transaction UX.',description:'Wallet connect states, send/receive actions, account summaries, and transaction history surfaces.'},
{id:'portfolio',label:'Portfolio',short:'Create a portfolio overview and holdings dashboard.',description:'Net worth, allocations, position cards, PnL widgets, and watchlist modules.'},
{id:'staking',label:'Staking',short:'Generate staking pages, validators, and reward states.',description:'Stake/unstake flows, APY displays, validator lists, and lockup analytics.'},
{id:'nft',label:'NFT',short:'Build an NFT marketplace, collection page, or mint flow.',description:'Collection grids, floor price cards, trait filters, mint interfaces, and analytics.'},
{id:'trading-terminal',label:'Trading / Terminal',short:'Create a Solana trading terminal and market view.',description:'Order books, fills, position tables, activity feeds, and trader-side utility panels.'},
{id:'token-analytics',label:'Token Analytics',short:'Generate a token analytics workspace with charts and tables.',description:'Volume, liquidity, holders, token distribution, and smart money modules.'},
{id:'admin',label:'Solana SaaS / Admin',short:'Design an internal admin surface for Solana teams.',description:'User management, queue states, ops metrics, billing panels, and moderation flows.'},
{id:'explorer',label:'Explorer-style Pages',short:'Build explorer-style addresses, blocks, or transaction pages.',description:'Address pages, transaction details, block explorer tables, and network status cards.'}
];
export const featureCards=[{title:'Prompt-to-code generation',description:'Use TALONS like a Solana-specific AI builder for pages, components, backend helpers, and docs.'},{title:'Preview-aware output',description:'Render UI outputs live. Non-visual code stays in code, logs, diff, and file views.'},{title:'Full workspace flow',description:'Builder, components, examples, docs, history, and generated file awareness are part of the core product.'},{title:'Extensible architecture',description:'Use the initial Solana use cases now and grow the registry with new templates and skills later.'}];
export const exampleCards=['Swap Interface','Meme Token Landing','Launchpad Dashboard','Wallet Overview','Staking Page','NFT Marketplace','Trading Terminal','Token Analytics','Protocol Dashboard','Explorer Address Page','Admin Console','Community Rewards Panel'];
export const componentsCatalog=['Action Box','Activity Feed','Address Display','Auth Card','Balance Widget','Chart Panel','Empty State','Health Bar','NFT Card','Order Book','Portfolio Table','Protocol KPI Grid','Rewards Card','Swap Form','Token Tile','Transaction Row','Validator Card','Wallet Header'];
export const docsNav=['Get Started','AI Builder','Skills','Examples','Components','Templates','Prompting Guide','Solana Use Cases','Preview Rules','File Structure','Troubleshooting'];
export const docsContent:Record<string,{title:string;intro:string;sections:{title:string;body:string}[]}>={
'get-started':{title:'Get Started',intro:'TALONS is a Solana-focused builder that turns prompts into working product surfaces, code changes, and live previews when the output is visual.',sections:[{title:'Builder-first workflow',body:'Start from Builder to describe the Solana surface you want. TALONS classifies the request, chooses an output path, and renders UI results inside Preview when possible.'},{title:'Visual and non-visual outputs',body:'Pages, components, dashboards, and sections open in Preview. Backend routes, helpers, configs, or docs stay in Code, Diff, Files, and Logs.'},{title:'Product areas',body:'The starter registry covers swap, meme token UI, launchpad, wallet UX, portfolio, staking, NFT, trading terminal, token analytics, protocol dashboards, admin screens, and explorer-style pages.'}]},
'ai-builder':{title:'AI Builder',intro:'Builder is the heart of TALONS. It combines prompt input, files, code, preview, history, and run diagnostics in one workspace.',sections:[{title:'Prompt chips',body:'Use chips as fast entry points or write your own custom Solana request in the composer.'},{title:'Output classification',body:'Every run is classified as visual or non-visual before TALONS decides whether to open Preview automatically.'},{title:'Iteration loop',body:'Use Improve, Fix, and Explain to continue refining the same workspace without leaving the builder flow.'}]},
'skills':{title:'Skills',intro:'Skills are file-aware routines that generate, patch, summarize, or structure work across the TALONS workspace.',sections:[{title:'Core skill groups',body:'Page Builder, Component Builder, Dashboard Builder, Docs Writer, Route Builder, Refactor, Fix, Preview Detector, and Diff Summarizer.'},{title:'File actions',body:'Skills create files, patch code, update docs, generate helper modules, and provide run summaries.'},{title:'Extending the registry',body:'You can add new use cases later without changing the core workspace shape.'}]},
'examples':{title:'Examples',intro:'Examples showcase complete Solana product flows and seed the Builder with a strong starting point.',sections:[{title:'Use-case library',body:'Examples include Swap Interface, Meme Token Landing, Launchpad Dashboard, Wallet Overview, Staking Page, NFT Marketplace, Trading Terminal, Token Analytics, and more.'},{title:'Builder handoff',body:'Open an example and continue iterating from the same workspace with your own prompt.'}]},
'components':{title:'Components',intro:'Components are reusable Solana UI building blocks with code snippets and visual previews.',sections:[{title:'Catalog structure',body:'Wallet, token, protocol, trading, NFT, analytics, table, status, and admin blocks are grouped by surface area.'},{title:'Usage flow',body:'Browse a component, understand its role, then add it to a generated page or builder run.'}]},
'templates':{title:'Templates',intro:'Templates accelerate high-value Solana surfaces while keeping the workspace extensible.',sections:[{title:'Starter templates',body:'Swap, Meme Token, Launchpad, Wallet, Portfolio, NFT, Staking, Trading Terminal, Protocol Dashboard, Explorer, and Admin Console.'},{title:'Custom adaptation',body:'Use templates as a starting point, then prompt TALONS to reshape the output for your product.'}]},
'prompting-guide':{title:'Prompting Guide',intro:'Strong prompts make TALONS faster, cleaner, and more predictable.',sections:[{title:'Be specific',body:'Mention the Solana product type, layout style, audience, data blocks, and any special states you need.'},{title:'Clarify output type',body:'Say whether you want a page, component, dashboard, backend route, helper, or docs content.'},{title:'Use iteration',body:'Prompt once for structure, then refine with Improve UI, Fix Errors, or Explain.'}]},
'solana-use-cases':{title:'Solana Use Cases',intro:'The first release is centered on Solana and its product surfaces.',sections:[{title:'Consumer flows',body:'Swap, wallet, portfolio, NFT, and staking experiences.'},{title:'Protocol flows',body:'Launchpad, protocol dashboards, token analytics, and explorer-style views.'},{title:'Operations flows',body:'Admin consoles, internal SaaS screens, moderation, monitoring, and treasury views.'}]},
'preview-rules':{title:'Preview Rules',intro:'Preview opens only when the output can be rendered as a UI surface.',sections:[{title:'Preview enabled',body:'Pages, components, dashboards, cards, sections, forms, widgets, and layouts.'},{title:'Preview disabled',body:'API routes, services, configs, helpers, docs content, parser logic, and workers.'},{title:'Run behavior',body:'When Preview is disabled, TALONS prioritizes Code, Files, Diff, and Logs.'}]},
'file-structure':{title:'File Structure',intro:'TALONS uses a repository-shaped workspace so users can understand generated output at the file level.',sections:[{title:'App and components',body:'Use app/ for routes and components/ for reusable product building blocks.'},{title:'Lib and docs',body:'Use lib/ for helpers, adapters, and route logic. Use docs/ for the internal documentation surface.'},{title:'Public and styles',body:'Use public/ for assets and styles/ for shared styling concerns.'}]},
'troubleshooting':{title:'Troubleshooting',intro:'When a run fails, TALONS keeps enough context in logs and diff to help you recover quickly.',sections:[{title:'Preview errors',body:'Check whether the output is actually visual. Non-visual runs never require Preview.'},{title:'Broken code',body:'Use Fix Errors to regenerate changed files and inspect Diff before applying another change.'},{title:'Run diagnostics',body:'Inspector and Logs explain classification, files touched, and why the result opened in Code or Preview.'}]}
};
